"""Guard tests for the COMMITTED sample story (plan §11 Step 13).

``projects/example_kids_story/`` is the one story that ships in the public
repo (root ``.gitignore`` re-include, plan §3.5). These tests run against the
committed tree itself — path relative to the repo root, no tmp copy — so any
future drift (someone deleting a file, nesting a git repo inside, or breaking
the encoding contract) fails CI, not a reader.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from conftest import REPO_ROOT, STORY_FILES, SUBFOLDERS
from shake_spear.utils import parse_frontmatter

SAMPLE = REPO_ROOT / "projects" / "example_kids_story"


def read(rel: str) -> str:
    return (SAMPLE / rel).read_text(encoding="utf-8")


def test_sample_story_dir_has_full_anatomy() -> None:
    """The §3.1 anatomy: all nine subfolders and all nine root story files."""
    assert SAMPLE.is_dir()
    for sub in SUBFOLDERS:
        assert (SAMPLE / sub).is_dir(), f"missing subfolder: {sub}"
    for name in STORY_FILES:
        assert (SAMPLE / name).is_file(), f"missing story file: {name}"
    assert (SAMPLE / ".claude" / "skills").is_dir()


def test_story_bible_frontmatter_is_filled() -> None:
    data = parse_frontmatter(read("story_bible.md"))
    assert data["genre"] == "kids"
    assert data["mode"] == "playful"
    assert isinstance(data["audience"], str) and data["audience"].strip()


@pytest.mark.parametrize(
    ("folder", "minimum"),
    [("characters", 2), ("world", 2), ("scenes", 2), ("drafts", 1), ("sessions", 1)],
)
def test_entity_folders_are_populated(folder: str, minimum: int) -> None:
    entries = list((SAMPLE / folder).glob("*.md"))
    assert len(entries) >= minimum, f"{folder}: {len(entries)} < {minimum}"


def test_index_lists_the_draft() -> None:
    assert "drafts/01_the_quiet_oven.md" in read("index.md")


def test_recap_block_is_populated() -> None:
    """`ss recap` ran on the final state: the marker block holds a real recap."""
    text = read("active_state.md")
    block = text.split("<!-- ss:recap:start -->")[1].split("<!-- ss:recap:end -->")[0]
    assert "Recap generated by `ss recap`" in block
    assert "ss recap writes the" not in block  # template placeholder is gone


def test_no_git_repo_nested_inside_sample() -> None:
    """--no-git held: the sample must not be a nested repo (plan §3.5)."""
    assert not (SAMPLE / ".git").exists()
    assert not list(SAMPLE.rglob(".git"))


# Local junk the sample's own .gitignore anticipates (editor/OS droppings). The
# encoding sweep guards SHIPPED content only — walking the live tree would
# false-fail on an untracked .DS_Store/Thumbs.db (review finding, Step 13).
_JUNK_NAMES = {".DS_Store", "Thumbs.db"}


def _is_junk(path: Path) -> bool:
    return (
        path.name in _JUNK_NAMES
        or path.name.startswith("~$")
        or path.suffix == ".pyc"
        or "__pycache__" in path.parts
    )


def test_every_file_is_utf8_lf_no_bom() -> None:
    for path in sorted(p for p in SAMPLE.rglob("*") if p.is_file() and not _is_junk(p)):
        raw = path.read_bytes()
        rel = path.relative_to(SAMPLE)
        assert not raw.startswith(b"\xef\xbb\xbf"), f"BOM in {rel}"
        assert b"\r" not in raw, f"CR byte in {rel}"
        raw.decode("utf-8")  # raises on invalid UTF-8
