"""Integration tests for ``ss export`` (plan §11 Step 11).

All tests go through the production CLI entry point — ``cli.main()``
in-process plus a true ``python -m shake_spear`` subprocess — against the
shared ``workshop``/``story`` fixtures (real templates/skills/skeleton, real
``new-story`` run). Drafts are hand-written files: ``drafts/`` has no creator
command by design (plan §3.4 — the operator's prose is never generated).
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

import pytest

from conftest import SLUG
from shake_spear.cli import main
from shake_spear.indexer import _draft_files

DERIVED_NOTE = "_(Derived file: regenerated by `ss export`; safe to overwrite.)_"


def manuscript_path(story: Path) -> Path:
    return story / "exports" / "manuscript.md"


def manuscript_text(story: Path) -> str:
    return manuscript_path(story).read_text(encoding="utf-8")


def write_draft(story: Path, name: str, content: str) -> Path:
    draft = story / "drafts" / name
    draft.write_text(content, encoding="utf-8")
    return draft


# ---------------------------------------------------------------------------
# ordering: lexicographic by filename, files only (plan §4 export row)
# ---------------------------------------------------------------------------


def test_parts_in_lexicographic_filename_order(story: Path) -> None:
    # Created deliberately OUT of lexicographic order. The unpadded 9_w
    # sorting AFTER 10_z ("1" < "9" stringwise) disambiguates lexicographic
    # from natural/numeric sort, and epilogue proves a prefix-less name
    # slots in lexicographically too.
    write_draft(story, "10_z.md", "Part ten.\n")
    write_draft(story, "02_y.md", "Part two.\n")
    write_draft(story, "epilogue.md", "The end.\n")
    write_draft(story, "9_w.md", "Part nine.\n")
    write_draft(story, "01_x.md", "Part one.\n")
    assert main(["export", SLUG]) == 0
    headings = [line for line in manuscript_text(story).splitlines() if line.startswith("## ")]
    assert headings == ["## 01_x.md", "## 02_y.md", "## 10_z.md", "## 9_w.md", "## epilogue.md"]


def test_only_files_and_only_toplevel_md_are_gathered(story: Path) -> None:
    write_draft(story, "01_x.md", "Real part.\n")
    (story / "drafts" / "folder.md").mkdir()  # a DIRECTORY matching the glob
    nested = story / "drafts" / "sub"
    nested.mkdir()
    (nested / "nested.md").write_text("Nested note.\n", encoding="utf-8")
    (story / "drafts" / "notes.txt").write_text("Not markdown.\n", encoding="utf-8")
    assert main(["export", SLUG]) == 0
    text = manuscript_text(story)
    assert "1 part.\n" in text
    assert "## 01_x.md" in text
    for absent in ("folder.md", "nested.md", "notes.txt", "Nested note", "Not markdown"):
        assert absent not in text


# ---------------------------------------------------------------------------
# content: header, headings, frontmatter stripped, bodies as prose
# ---------------------------------------------------------------------------


def test_header_heading_and_body_layout(story: Path) -> None:
    write_draft(story, "01_x.md", "Once upon an orbit.\n")
    write_draft(story, "02_y.md", "The bakery rose at dawn.\n")
    assert main(["export", SLUG]) == 0
    assert manuscript_text(story) == (
        "# Manuscript\n"
        "\n"
        f"{DERIVED_NOTE}\n"
        "\n"
        "2 parts.\n"
        "\n"
        "## 01_x.md\n"
        "\n"
        "Once upon an orbit.\n"
        "\n"
        "## 02_y.md\n"
        "\n"
        "The bakery rose at dawn.\n"
    )


def test_frontmatter_only_draft_yields_bare_heading_no_dangling_body(story: Path) -> None:
    write_draft(story, "01_x.md", "---\ntitle: Outline Stub\nstatus: raw\n---\n")
    write_draft(story, "02_y.md", "Real prose.\n")
    assert main(["export", SLUG]) == 0
    assert manuscript_text(story) == (
        f"# Manuscript\n\n{DERIVED_NOTE}\n\n2 parts.\n\n## 01_x.md\n\n## 02_y.md\n\nReal prose.\n"
    )


def test_draft_frontmatter_stripped_from_manuscript(story: Path) -> None:
    write_draft(
        story,
        "01_x.md",
        "---\ntitle: Chapter One\nstatus: raw\ntags: [space, bread]\n---\nBody prose only.\n",
    )
    assert main(["export", SLUG]) == 0
    text = manuscript_text(story)
    assert "Body prose only." in text
    assert "## 01_x.md" in text
    for leaked in ("---", "title:", "status:", "tags:"):
        assert leaked not in text


# ---------------------------------------------------------------------------
# empty drafts: friendly message, exit 0, nothing written (documented choice)
# ---------------------------------------------------------------------------


def test_fresh_story_prints_friendly_message_writes_nothing(
    story: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    assert main(["export", SLUG]) == 0
    assert capsys.readouterr().out.strip() == "(no drafts yet — nothing to export)"
    assert not manuscript_path(story).exists()


def test_empty_drafts_with_out_override_also_writes_nothing(
    workshop: Path, story: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    assert main(["export", SLUG, "--out", "somewhere/else.md"]) == 0
    assert "no drafts yet" in capsys.readouterr().out
    assert not (workshop / "somewhere").exists()


# ---------------------------------------------------------------------------
# drafts strictly read-only (plan §3.4): bytes AND mtimes unchanged
# ---------------------------------------------------------------------------


def test_drafts_byte_identical_and_mtime_unchanged(story: Path) -> None:
    drafts = [
        write_draft(story, "01_x.md", "---\nstatus: raw\n---\nPart one.\n"),
        write_draft(story, "02_y.md", "Part two.\n"),
    ]
    before = [(d.read_bytes(), d.stat().st_mtime_ns) for d in drafts]
    assert main(["export", SLUG]) == 0
    after = [(d.read_bytes(), d.stat().st_mtime_ns) for d in drafts]
    assert after == before


# ---------------------------------------------------------------------------
# derived-artifact semantics: overwrite freely, no .bak, idempotent (plan §3.4)
# ---------------------------------------------------------------------------


def test_second_run_overwrites_without_bak_and_is_byte_identical(story: Path) -> None:
    write_draft(story, "01_x.md", "Part one.\n")
    assert main(["export", SLUG]) == 0  # NOT exit 2 - the default target needs no --force
    first = manuscript_path(story).read_bytes()
    assert main(["export", SLUG]) == 0
    assert manuscript_path(story).read_bytes() == first
    assert list(story.rglob("*.bak-*")) == [], "derived overwrite must not create backups"
    # Guard the no-timestamp invariant (same rationale as index.md's).
    assert not re.search(r"\b\d{2}:\d{2}(:\d{2})?\b", first.decode("utf-8"))


def test_export_reflects_draft_edits_on_regeneration(story: Path) -> None:
    draft = write_draft(story, "01_x.md", "Old prose.\n")
    assert main(["export", SLUG]) == 0
    draft.write_text("New prose.\n", encoding="utf-8")
    assert main(["export", SLUG]) == 0
    text = manuscript_text(story)
    assert "New prose." in text
    assert "Old prose." not in text


# ---------------------------------------------------------------------------
# --out override: relative to cwd, parents created, default target untouched
# ---------------------------------------------------------------------------


def test_out_relative_resolves_against_cwd_and_creates_parents(
    workshop: Path, story: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    write_draft(story, "01_x.md", "Part one.\n")
    assert main(["export", SLUG, "--out", "build/deep/book.md"]) == 0
    target = workshop / "build" / "deep" / "book.md"  # cwd is the workshop root
    assert capsys.readouterr().out.strip() == str(target)
    assert "## 01_x.md" in target.read_text(encoding="utf-8")
    assert not manuscript_path(story).exists(), "--out must replace the default target"


def test_out_absolute_path(tmp_path: Path, story: Path) -> None:
    write_draft(story, "01_x.md", "Part one.\n")
    target = tmp_path / "elsewhere" / "manuscript.md"
    assert main(["export", SLUG, "--out", str(target)]) == 0
    assert "Part one." in target.read_text(encoding="utf-8")


# ---------------------------------------------------------------------------
# --out guards (iter 2): drafts/ rejection, refuse/backup for existing
# targets, self-concatenation exclusion, clean error for unwritable targets
# ---------------------------------------------------------------------------


def test_out_pointing_at_existing_draft_rejected_exit_1(
    story: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    draft = write_draft(story, "01_x.md", "Operator prose - never clobber.\n")
    before = draft.read_bytes()
    assert main(["export", SLUG, "--out", str(draft)]) == 1
    assert "--out may not point inside drafts/" in capsys.readouterr().err
    assert draft.read_bytes() == before, "the draft must be untouched"
    # --force must NOT bypass the drafts/ rejection either.
    assert main(["export", SLUG, "--out", str(draft), "--force"]) == 1
    assert draft.read_bytes() == before


def test_out_new_or_nested_name_inside_drafts_also_rejected(
    story: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    write_draft(story, "01_x.md", "Part one.\n")
    for rel in ("new_name.md", "sub/deep.md"):
        target = story / "drafts" / rel
        assert main(["export", SLUG, "--out", str(target)]) == 1
        assert "--out may not point inside drafts/" in capsys.readouterr().err
        assert not target.exists()


def test_out_existing_file_refused_exit_2_without_force(
    workshop: Path, story: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    write_draft(story, "01_x.md", "Part one.\n")
    precious = workshop / "precious.md"
    precious.write_text("Operator prose - do not lose.\n", encoding="utf-8")
    assert main(["export", SLUG, "--out", str(precious)]) == 2
    assert "--force" in capsys.readouterr().err
    assert precious.read_text(encoding="utf-8") == "Operator prose - do not lose.\n"
    assert list(workshop.glob("*.bak-*")) == []


def test_out_existing_file_force_backs_up_overwrites_and_prints_backup(
    workshop: Path, story: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    write_draft(story, "01_x.md", "Part one.\n")
    precious = workshop / "precious.md"
    precious.write_text("Old operator prose.\n", encoding="utf-8")
    assert main(["export", SLUG, "--out", str(precious), "--force"]) == 0
    out = capsys.readouterr().out
    backups = list(workshop.glob("precious.md.bak-*"))
    assert len(backups) == 1
    assert backups[0].read_text(encoding="utf-8") == "Old operator prose.\n"
    assert str(precious) in out
    assert str(backups[0]) in out
    assert "## 01_x.md" in precious.read_text(encoding="utf-8")


def test_out_spelling_the_default_path_keeps_derived_semantics(story: Path) -> None:
    write_draft(story, "01_x.md", "Part one.\n")
    assert main(["export", SLUG]) == 0  # the default manuscript now exists
    # Re-export --out pointing AT the default: still derived — no --force
    # needed (exit 0, not 2), no .bak- backup created.
    assert main(["export", SLUG, "--out", str(manuscript_path(story))]) == 0
    assert list(story.rglob("*.bak-*")) == []


def test_draft_set_excludes_resolved_export_target(story: Path) -> None:
    # Defense in depth: through the CLI the drafts/-tree rejection fires
    # first, so the exclusion only matters for aliased paths (e.g. a
    # symlinked draft resolving to an outside-drafts/ target, which needs
    # privileges to create on Windows) — assert the helper contract directly.
    first = write_draft(story, "01_x.md", "Part one.\n")
    write_draft(story, "02_y.md", "Part two.\n")
    assert [p.name for p in _draft_files(story)] == ["01_x.md", "02_y.md"]
    assert [p.name for p in _draft_files(story, exclude=first.resolve())] == ["02_y.md"]


def test_out_existing_directory_exits_1_with_clean_error(
    tmp_path: Path, story: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    write_draft(story, "01_x.md", "Part one.\n")
    outdir = tmp_path / "outdir"
    outdir.mkdir()
    assert main(["export", SLUG, "--out", str(outdir)]) == 1  # UsageError, not a traceback
    assert "cannot write manuscript to" in capsys.readouterr().err


# ---------------------------------------------------------------------------
# CRLF drafts → LF-only manuscript (plan §3.4)
# ---------------------------------------------------------------------------


def test_crlf_draft_yields_cr_free_manuscript(story: Path) -> None:
    (story / "drafts" / "windows.md").write_bytes(
        b"---\r\ntitle: Windows Draft\r\n---\r\nLine one from CRLF land.\r\nLine two.\r\n"
    )
    assert main(["export", SLUG]) == 0
    raw = manuscript_path(story).read_bytes()
    assert b"\r" not in raw
    assert raw[:1] != b"\xef", "no BOM"
    assert "Line one from CRLF land.\nLine two." in manuscript_text(story)


# ---------------------------------------------------------------------------
# CLI contract: optional PROJECT, printed path (plan §4)
# ---------------------------------------------------------------------------


def test_project_omitted_cwd_inside_story(story: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    write_draft(story, "01_x.md", "Part one.\n")
    monkeypatch.chdir(story / "drafts")  # deep inside: walk-up must find the story root
    assert main(["export"]) == 0
    assert manuscript_text(story).startswith("# Manuscript")


def test_project_omitted_outside_story_exits_1(
    workshop: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    assert main(["export"]) == 1
    assert "no PROJECT given" in capsys.readouterr().err


def test_prints_manuscript_path(story: Path, capsys: pytest.CaptureFixture[str]) -> None:
    write_draft(story, "01_x.md", "Part one.\n")
    assert main(["export", SLUG]) == 0
    assert capsys.readouterr().out.strip() == str(manuscript_path(story))


# ---------------------------------------------------------------------------
# true subprocess test through python -m shake_spear
# ---------------------------------------------------------------------------


def test_subprocess_export(workshop: Path, story: Path) -> None:
    write_draft(story, "01_x.md", "Part one.\n")
    result = subprocess.run(
        [sys.executable, "-m", "shake_spear", "export", SLUG],
        cwd=workshop,
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, result.stderr
    assert result.stdout.strip() == str(manuscript_path(story))
    assert "## 01_x.md" in manuscript_text(story)
