"""Integration tests for ``ss recap`` / ``ss status`` (plan §11 Step 10).

THE load-bearing guarantee (plan §3.4): recap rewrites ONLY the text between
the ``ss:recap`` markers in ``active_state.md`` — every byte outside them
(operator CRLF lines, trailing whitespace, tabs) survives verbatim. All tests
drive the production CLI — ``cli.main()`` in-process plus one true
``python -m shake_spear`` subprocess — against the shared conftest fixtures
(real templates/skeleton, real ``new-story`` run).
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

from conftest import SLUG
from shake_spear import session
from shake_spear.cli import main

DATE = "2026-07-02"

#: Literal marker lines (plan Appendix B) — NOT imported from session.py, so
#: drift in the shipped constants fails against the plan, not against itself.
START = b"<!-- ss:recap:start -->"
END = b"<!-- ss:recap:end -->"

#: Operator-authored bytes BEFORE the marker block: a UTF-8 BOM, mixed CRLF
#: and LF lines, plus a trailing-whitespace quirk — recap must preserve all
#: of it verbatim.
PREFIX = (
    b"\xef\xbb\xbf# Active State\r\n"
    b"\r\n"
    b"## Current status\n"
    b"\n"
    b"Drafting chapter two; Nova just found the oven.   \n"
    b"\n"
    b"## Open loops\n"
    b"\n"
    b"- Who lit the pilot light?\n"
    b"- Why does the dough sing?\n"
    b"\n"
    b"## Next tiny action\n"
    b"\n"
    b"Write the first two lines of the kitchen argument.\n"
    b"\n"
)

#: Operator-authored bytes AFTER the marker block: CRLF, a tab, trailing
#: spaces, and a whitespace-only final line.
SUFFIX = b"\r\n\r\n## Notes for AI assistants\r\nKeep it cozy. \t\r\n   \r\n"


@pytest.fixture()
def frozen_date(monkeypatch: pytest.MonkeyPatch) -> str:
    """Pin ``session._today`` so the dated recap first line is deterministic."""
    monkeypatch.setattr(session, "_today", lambda: DATE)
    return DATE


def _author_active_state(story: Path) -> bytes:
    """Overwrite active_state.md with the quirk-laden operator file; return its bytes."""
    raw = PREFIX + START + b"\nOLD RECAP CONTENT\n" + END + SUFFIX
    (story / "active_state.md").write_bytes(raw)
    return raw


def _block_text(story: Path) -> str:
    """The text between the markers in the story's active_state.md."""
    text = (story / "active_state.md").read_text(encoding="utf-8")
    return text.split(START.decode(), 1)[1].split(END.decode(), 1)[0]


def _write_log(story: Path, name: str, body: str = "# Writing Session\n") -> None:
    """Drop a session log with a chosen filename (dates vary across logs)."""
    (story / "sessions" / name).write_text(body, encoding="utf-8")


# ---------------------------------------------------------------------------
# THE load-bearing test: surgical marker-block rewrite (plan §3.4)
# ---------------------------------------------------------------------------


def test_recap_rewrites_only_the_marker_block(
    story: Path, frozen_date: str, capsys: pytest.CaptureFixture[str]
) -> None:
    _author_active_state(story)
    capsys.readouterr()  # drop story-fixture output
    assert main(["recap", SLUG]) == 0
    path = story / "active_state.md"
    assert capsys.readouterr().out.strip().splitlines() == [str(path)]
    raw = path.read_bytes()
    assert raw.startswith(PREFIX + START), "bytes before/through the start marker changed"
    assert raw.endswith(END + SUFFIX), "bytes from the end marker to EOF changed"
    block = raw[len(PREFIX + START) : len(raw) - len(END + SUFFIX)].decode("utf-8")
    assert "OLD RECAP CONTENT" not in block, "the between-markers text must be replaced"
    assert "ss:recap:" not in block, (
        "the new block must never nest marker lines (recap reading its own old output)"
    )
    assert f"_Recap generated by `ss recap` on {DATE}." in block, "dated first line"
    assert "**Current state:** Drafting chapter two; Nova just found the oven." in block
    assert "- Who lit the pilot light?" in block
    assert "- Why does the dough sing?" in block
    assert "Write the first two lines of the kitchen argument." in block


def test_generated_block_is_lf_only(story: Path, frozen_date: str) -> None:
    _author_active_state(story)
    assert main(["recap", SLUG]) == 0
    raw = (story / "active_state.md").read_bytes()
    between = raw[raw.find(START) + len(START) : raw.find(END)]
    assert b"\r" not in between, "the generated block itself must be LF-only"


def test_recap_twice_same_day_is_idempotent(story: Path, frozen_date: str) -> None:
    _author_active_state(story)
    assert main(["recap", SLUG]) == 0
    first = (story / "active_state.md").read_bytes()
    assert main(["recap", SLUG]) == 0
    assert (story / "active_state.md").read_bytes() == first, (
        "a second same-day recap must leave the file byte-identical"
    )


def test_recap_leaves_no_temp_residue(story: Path, frozen_date: str) -> None:
    """The atomic sibling-temp + os.replace write must clean up after itself."""
    _author_active_state(story)
    assert main(["recap", SLUG]) == 0
    residue = [path.name for path in story.iterdir() if ".tmp" in path.name]
    assert residue == [], f"recap left temp files behind: {residue}"


# ---------------------------------------------------------------------------
# line-anchored markers: prose MENTIONS of a marker string are never markers
# ---------------------------------------------------------------------------

#: Operator prose that mentions the marker strings without authoring marker
#: LINES: inline in a sentence, alone-on-a-line but backticked, and inside a
#: code fence with surrounding text. None of these may latch the surgery.
PROSE_MENTIONS = (
    b"## Notes for AI assistants\r\n"
    b"\r\n"
    b"The text between <!-- ss:recap:start --> and <!-- ss:recap:end --> is generated.\r\n"
    b"`<!-- ss:recap:start -->`\r\n"
    b"```\r\n"
    b"see <!-- ss:recap:start --> in active_state.md\r\n"
    b"```\r\n"
    b"\r\n"
)


def test_prose_marker_mentions_above_real_block_are_untouched(
    story: Path, frozen_date: str
) -> None:
    """Marker strings quoted in prose/fences above a REAL marker block: the
    surgery must replace the real block and leave the prose byte-identical."""
    (story / "active_state.md").write_bytes(
        PREFIX + PROSE_MENTIONS + START + b"\nOLD RECAP CONTENT\n" + END + SUFFIX
    )
    assert main(["recap", SLUG]) == 0
    raw = (story / "active_state.md").read_bytes()
    assert raw.startswith(PREFIX + PROSE_MENTIONS + START), (
        "prose mentions above the real block must survive byte-identically"
    )
    assert raw.endswith(END + SUFFIX), "bytes from the real end marker to EOF changed"
    assert b"OLD RECAP CONTENT" not in raw, "the real block must be the one replaced"
    assert b"Recap generated by" in raw


def test_prose_only_marker_mention_appends_new_block(story: Path, frozen_date: str) -> None:
    """An inline mention is NOT a marker line — with no real block anywhere,
    recap takes the append path and the prose survives byte-identically."""
    original = PREFIX + b"See <!-- ss:recap:start --> and <!-- ss:recap:end --> in the docs.\r\n"
    (story / "active_state.md").write_bytes(original)
    assert main(["recap", SLUG]) == 0
    raw = (story / "active_state.md").read_bytes()
    assert raw.startswith(original), "the prose mention must survive byte-identically"
    appended = raw[len(original) :]
    assert appended.startswith(b"\n" + START + b"\n")
    assert appended.endswith(b"\n" + END + b"\n")
    assert b"Recap generated by" in appended


def test_multiple_marker_pairs_exit_1_file_unchanged(
    story: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """Two complete marker blocks: recap must refuse (which one is THE block?)."""
    original = (
        PREFIX
        + START
        + b"\nfirst block\n"
        + END
        + b"\n\r\noperator prose between blocks\r\n\r\n"
        + START
        + b"\nsecond block\n"
        + END
        + SUFFIX
    )
    (story / "active_state.md").write_bytes(original)
    capsys.readouterr()
    assert main(["recap", SLUG]) == 1
    assert "multiple recap marker blocks found - remove the duplicates" in capsys.readouterr().err
    assert (story / "active_state.md").read_bytes() == original, (
        "a duplicated-block file must not be touched"
    )


# ---------------------------------------------------------------------------
# markers absent -> append at EOF; corrupt marker state -> exit 1, untouched
# ---------------------------------------------------------------------------


def test_markers_absent_appends_block_at_eof(story: Path, frozen_date: str) -> None:
    original = PREFIX + b"## Notes for AI assistants\r\nKeep it cozy. \t\r\n"
    (story / "active_state.md").write_bytes(original)
    assert main(["recap", SLUG]) == 0
    raw = (story / "active_state.md").read_bytes()
    assert raw.startswith(original), "original content must be a byte-identical prefix"
    appended = raw[len(original) :]
    assert appended.startswith(b"\n" + START + b"\n")
    assert appended.endswith(b"\n" + END + b"\n")
    assert raw.count(START) == 1 and raw.count(END) == 1, "markers now present exactly once"
    assert b"Recap generated by" in appended


@pytest.mark.parametrize("stray", [START, END], ids=["start-only", "end-only"])
def test_single_stray_marker_exits_1_file_unchanged(
    story: Path, stray: bytes, capsys: pytest.CaptureFixture[str]
) -> None:
    original = PREFIX + stray + b"\n" + SUFFIX
    (story / "active_state.md").write_bytes(original)
    capsys.readouterr()
    assert main(["recap", SLUG]) == 1
    assert "stray marker" in capsys.readouterr().err
    assert (story / "active_state.md").read_bytes() == original, (
        "a corrupt-marker file must not be touched"
    )


def test_out_of_order_markers_exit_1_file_unchanged(
    story: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    original = PREFIX + END + b"\nweird\n" + START + SUFFIX
    (story / "active_state.md").write_bytes(original)
    capsys.readouterr()
    assert main(["recap", SLUG]) == 1
    assert "marker order" in capsys.readouterr().err
    assert (story / "active_state.md").read_bytes() == original


# ---------------------------------------------------------------------------
# content: placeholders on a fresh story; latest-3 sessions; continuity
# ---------------------------------------------------------------------------


def test_fresh_story_zero_sessions_writes_placeholders(
    story: Path, frozen_date: str, capsys: pytest.CaptureFixture[str]
) -> None:
    """The scaffolded story (no sessions, empty sections) still exits 0 (plan §4)."""
    capsys.readouterr()
    assert main(["recap", SLUG]) == 0
    assert capsys.readouterr().out.strip().splitlines() == [str(story / "active_state.md")]
    block = _block_text(story)
    assert session.NO_SESSIONS_YET in block
    assert "**Latest sessions:** (none yet)" in block
    assert "**Open loops:** (none recorded)" in block
    assert "**Continuity notes:** (none recorded)" in block
    assert "**Story so far:** 0 scenes, 0 characters, 0 world elements, 0 drafts" in block
    assert session.NO_NEXT_ACTION in block


#: A >80-char next tiny action — the recap bullet must truncate it with "...".
LONG_ACTION = (
    "Finish the kitchen argument scene where Nova finally admits she fed the "
    "sourdough starter to the gravity oven on purpose"
)


def test_recap_lists_exactly_three_latest_sessions(story: Path, frozen_date: str) -> None:
    """4 logs across 2 dates -> the 3 newest by filename sort desc, with snippets."""
    assert len(LONG_ACTION) > 80, "fixture must exceed the 80-char snippet cap"
    _write_log(story, "2026-07-01_scene_45min.md", "## Session goal\n\nOld goal line.\n")
    _write_log(story, "2026-07-01_scene_45min_b.md")
    _write_log(
        story,
        "2026-07-02_scene_45min.md",
        f"## Session goal\n\nGoal line.\n\n## Next tiny action\n\n{LONG_ACTION}\n",
    )
    _write_log(story, "2026-07-02_freewrite_15min.md", "## Session goal\n\nMorning pages.\n")
    assert main(["recap", SLUG]) == 0
    block = _block_text(story)
    assert f"- `2026-07-02_scene_45min.md` — {LONG_ACTION[:77]}..." in block, (
        "Next tiny action is preferred over Session goal; >80 chars truncates to 77 + '...'"
    )
    assert LONG_ACTION not in block, "the full >80-char line must not appear untruncated"
    assert "- `2026-07-02_freewrite_15min.md` — Morning pages." in block, (
        "Session goal is the fallback snippet"
    )
    assert "- `2026-07-01_scene_45min_b.md`" in block, "sectionless log lists as bare filename"
    assert "2026-07-01_scene_45min.md" not in block, "the 4th-newest log must not be listed"
    assert block.count("\n- `") == 3, "exactly 3 session bullets"


def test_single_session_renders_as_block_list(story: Path, frozen_date: str) -> None:
    """One session must still render label-then-bullet — an inline
    '**Latest sessions:** - `x`' would not render as a markdown list."""
    _write_log(story, "2026-07-02_scene_45min.md", "## Session goal\n\nGoal line.\n")
    assert main(["recap", SLUG]) == 0
    block = _block_text(story)
    assert "**Latest sessions:**\n- `2026-07-02_scene_45min.md` — Goal line." in block


def test_recap_counts_entities_and_summarizes_continuity(
    story: Path, frozen_date: str, capsys: pytest.CaptureFixture[str]
) -> None:
    capsys.readouterr()
    assert main(["scene", SLUG, "Oven Door"]) == 0
    assert main(["scene", SLUG, "Kitchen Argument"]) == 0
    assert main(["character", SLUG, "Nova"]) == 0
    (story / "continuity.md").write_text(
        "---\ntype: continuity\nstatus: active\n---\n\n# Continuity Log\n\n"
        "## Timeline events\n\n- Day 1: oven found.\n- Day 2: dough sings.\n\n"
        "## Character facts\n\n- Nova is twelve.\n",
        encoding="utf-8",
    )
    assert main(["recap", SLUG]) == 0
    block = _block_text(story)
    assert "**Story so far:** 2 scenes, 1 character, 0 world elements, 0 drafts" in block
    assert (
        "**Continuity notes:** 3 note lines in continuity.md "
        "under Timeline events, Character facts" in block
    )
    # count==1 uses the singular noun (re-run recap after shrinking the log).
    (story / "continuity.md").write_text(
        "# Continuity Log\n\n## Character facts\n\n- Nova is twelve.\n",
        encoding="utf-8",
    )
    assert main(["recap", SLUG]) == 0
    block = _block_text(story)
    assert "**Continuity notes:** 1 note line in continuity.md under Character facts" in block, (
        "a single note must render as '1 note line', not '1 note lines'"
    )


# ---------------------------------------------------------------------------
# ss status: stdout only, writes nothing (plan §4)
# ---------------------------------------------------------------------------


def _file_snapshot(story: Path) -> dict[Path, bytes]:
    return {path: path.read_bytes() for path in sorted(story.rglob("*")) if path.is_file()}


def test_status_prints_fields_and_newest_session_writes_nothing(
    story: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    _author_active_state(story)
    _write_log(story, "2026-07-01_scene_45min.md")
    _write_log(story, "2026-07-02_scene_45min.md")
    before = _file_snapshot(story)
    capsys.readouterr()
    assert main(["status", SLUG]) == 0
    out = capsys.readouterr().out
    assert "Current status: Drafting chapter two; Nova just found the oven." in out
    assert "Current scene or chapter: (not set)" in out, "missing section falls back"
    assert "Open loops:" in out
    assert "- Who lit the pilot light?" in out
    assert "Next tiny action: Write the first two lines of the kitchen argument." in out
    assert "Newest session: 2026-07-02_scene_45min.md" in out
    assert _file_snapshot(story) == before, "status must write nothing"


def test_status_fresh_story_all_not_set(story: Path, capsys: pytest.CaptureFixture[str]) -> None:
    capsys.readouterr()
    assert main(["status", SLUG]) == 0
    out = capsys.readouterr().out
    for label in session.STATUS_SECTIONS:
        assert f"{label}: (not set)" in out
    assert "Newest session: (none)" in out


# ---------------------------------------------------------------------------
# true subprocess test through python -m shake_spear
# ---------------------------------------------------------------------------


def test_subprocess_recap_is_surgical(workshop: Path, story: Path) -> None:
    _author_active_state(story)
    result = subprocess.run(
        [sys.executable, "-m", "shake_spear", "recap", SLUG],
        cwd=workshop,
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, result.stderr
    assert result.stdout.strip().splitlines() == [str(story / "active_state.md")]
    raw = (story / "active_state.md").read_bytes()
    assert raw.startswith(PREFIX + START), "subprocess run must preserve the prefix bytes"
    assert raw.endswith(END + SUFFIX), "subprocess run must preserve the suffix bytes"
    assert b"OLD RECAP CONTENT" not in raw
    assert b"Recap generated by" in raw
